version: '3'

services:
  node:
    image: node:latest
    volumes:
      - /home/kevin/Desktop/node:/app
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - /home/kevin/Desktop/node/data:/data/db
    ports:
      - 27017:27017
